


# ??????
server:
  port: 8098

# Spring ????
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spider?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

# Mybatis-Plus ??
mybatis-plus:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: xx.magic.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazyLoadingEnabled: true
    multipleResultSetsEnabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
