
# 服务端口配置
server:
  port: 8089


spring:
  # 邮箱配置
  mail:
    host: smtp.qq.com
    port: 587
    username: 756316064@qq.com
    password: ijkieidasyzzbgaa
    # 编码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
  # thymeleaf 模板配置
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates
    suffix: .html


send:
  from: 756316064@qq.com
  authCode: ijkieidasyzzbgaa
  sendMail: 756316064@qq.com
