

# 服务端口配置
server:
  port: 8082

# Spring 相关配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/halo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  # 模板引擎配置
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/views/
    suffix: .html


# 文件存储位置
file:
  path: F:/tmp/