

# 服务端口配置
server:
  port: 8081

# Spring 相关配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/halo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 模板引擎配置
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/views/
    suffix: .html


mybatis:
  #标注待解析的mapper的xml文件位置
  mapper-locations: classpath:mapper/*.xml
  #标注实体类位置
  type-aliases-package: xx.student.entity



#分页插件
pagehelper:
  #指明数据库
  helper-dialect: mysql
  params: count=countSql
  #为true pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: true
  supportMethodsArguments: true
