
server:
  port: 8081

spring:
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates
    suffix: .html

  #配置rabbitMq 服务器
  rabbitmq:
    #地址
    host: 192.168.52.182
    #端口号
    port: 5672
    #用户名
    username: guest
    #密码
    password: guest
    #连接超时时间
    connection-timeout: 15000s

