
server:
  port: 8082

spring:
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates
    suffix: .html

  #Redis配置
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 5000
    database: 1


profile:
  enable: true



person:
  userName: lig
  boss: true
  # 默认是/开头
  birth: 2022/06/05
  age: 11
  # 对象
  pet:
    name: pet
    weight: 12.00
  interests:
    # -表示的是一个元素
    - 篮球
    - 足球
    - 音乐
  animal: [狗,猫,鸟]
  score:
    chinese: 12
    math: 12
    english: 88
  salarys: [12.03,12.52,47.12]
  allPets:
    sick:
      - name: a
        weight: 22.0
      - name: b
        weight: 23.07
    health:
      - name: c
        weight: 24.09
      - name: d
        weight: 25.02




